version: '2'
services:
  desk:
    volumes:
      - ".:/app:rw"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongo
  mongo:
    command: mongod
    image: mongo:3.2.0
    ports:
      - "27100:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none
  nginx:
    build:
      context: ./service/nginx
      dockerfile: ./Dockerfile.dev
    volumes:
      - "./logs/nginx:/image_logs:rw"
    logging:
      driver: json-file
    ports:
      - "3000:80"
    depends_on:
      - desk